# Generated by Django 3.2.2 on 2021-05-14 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_connected',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 15, 23, 57, 582661)),
        ),
    ]
