# Generated by Django 3.2.2 on 2021-05-16 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_comment_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_connected',
            new_name='product_connected',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 17, 0, 10, 242948)),
        ),
    ]
