# Generated by Django 3.2.2 on 2021-05-17 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_comment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='task_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 18, 50, 32, 241883)),
        ),
    ]
