# Generated by Django 3.2.2 on 2021-05-23 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210521_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 12, 15, 37, 849779)),
        ),
    ]
