# Generated by Django 3.2.2 on 2021-05-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='profile_pics'),
        ),
    ]
