# Generated by Django 3.1.6 on 2021-02-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_place',
        ),
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeworkapp.ceo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='head_of_department',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homeworkapp.department'),
            preserve_default=False,
        ),
    ]
