# Generated by Django 3.1.6 on 2021-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0002_auto_20210221_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_description',
            field=models.TextField(),
        ),
    ]
